// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseEchats: typeof import('./../src/components/base-echats/index.vue')['default']
    ElIcons: typeof import('./../src/components/el-icons/index.vue')['default']
    FlowCard: typeof import('./../src/components/flow-card/index.vue')['default']
    Language: typeof import('./../src/components/language/index.vue')['default']
    Markdown: typeof import('./../src/components/markdown/index.vue')['default']
    SvgIcon: typeof import('./../src/components/svg-icon/index.vue')['default']
    Viewer: typeof import('./../src/components/markdown/viewer.vue')['default']
  }
}

export { }
